### ISSUE TITLE
LightGraphs version in the benchmark

### ISSUE THREAD

**Issue by pzhanggit** [timlrx/graph-benchmarks#11]
Hi @timlrx, thanks for the very interesting work. I am trying to run the benchmarks following your instructions but have some troubles running lightgraphs.jl. I am using the LightGraphs master branch as suggested in the file (and also the master branch of graph-benchmarks), but it seems to have different implementations about functions like ShortestPaths and Centrality with the ones expected in lightgraphs.jl. For example, I found LightGraphs.ShortestPaths as LightGraphs.Experimental.ShortestPaths, but could not find ThreadedBFS and Centrality. Could you provide suggestions on which version I should use to run the lightgraphs.jl benchmark? Thanks!

**Comment by timlrx** [comment]
Hi @pzhanggit, yes this benchmark is a little old and some of the APIs may not be compatible with the latest version of the code. There's also a change in the structure of the repo, see this [thread](https://github.com/JuliaGraphs/LightGraphs.jl/issues/1506) for more info. Basically, master has reverted to the v1 code and development holds the v2.0-dev code. Try downloading that branch instead.

**Comment by pzhanggit** [comment]
Thank you, @timlrx! It is running now with the development branch.
